[tool.poetry]
name = "lecture_scanner"
version = "0.1.0"
description = ""
authors = ["jadenPete <jadenpete@github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
opencv-python = "^4.6.0.66"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
